name: GitHub-3D-Profile

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-3d-profile
    steps:
      - uses: actions/checkout@v5
      - uses: xarthurx/github-3d-profile@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: settings/theme-preview.json
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated: profile-3d-contrib [skip ci]"; then
            git pull --rebase
            git push
          fi
